apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploy_view 
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["deployments", "pods"]
  verbs: ["get", "watch", "list"]
