apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-namespace-admin 
  namespace: default 
subjects:
- kind: ServiceAccount
  name: sa-namespace-admin
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
