apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod_viewer
  namespace: prod
subjects:
- kind: User 
  name: prod_viewer 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view 
  apiGroup: rbac.authorization.k8s.io
